[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
dev = [
  "fastapi>= 0.78.0",
  "httpx>=0.28.1,<0.29",
  "isort>=6.0.1,<7",
  "pre-commit>=4.2.0,<5",
  "pytest-asyncio>=1.4.0,<2",
  "pytest-cov>=7.1.0,<8",
  "pytest>=8.4.1,<9",
  "ruff>=0.12.3,<0.17"
]

[project]
authors = [{email = "mattcoul7@gmail.com", name = "Matthew Coulter"}]
dependencies = [
  "deepdiff>=8.5.0,<9",
  "generic-preserver>=0.1.4,<0.2",
  "pydantic-settings>=2.10.1,<3",
  "pydantic>=2.11.7,<3",
  "pyyaml>=6.0.0,<7",
]
description = ""
name = "pydantic-di"
readme = "README.md"
requires-python = ">=3.12, <4"
version = "0.3.1"

[project.optional-dependencies]
fastapi = ["fastapi>= 0.78.0"]
all = [
    "attrs>=22.2.0",
]
attrs-plugin = [
    "attrs>=22.2.0",  # this version matches attrs used by the openapi cli generator
]

[tool.hatch.build.targets.sdist]
include = ["src/pydantic_di"]

[tool.hatch.build.targets.wheel]
packages = ["src/pydantic_di"]

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "session"
asyncio_mode = "auto"
markers = [
  "integration: Assigns the test to the integration test suite.",
  "regression: Assigns the test to the regression test suite"
]

[tool.ruff]
line-length = 120
src = ["src"]
target-version = "py312"

[tool.ruff.lint]
exclude = [".git", ".venv", "__pycache__", "proto"]
fixable = ["ALL"]
ignore = [
  "D104" # missing docstring in public package
]
select = [
  "ARG001", # unused arguments
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "D", # pydocstyle (docstring checks)
  "E", # pycodestyle errors
  "F", # pyflakes
  "I", # isort
  "UP", # pyupgrade
  "W" # pycodestyle warnings
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D", "ARG001", "B008"]
